# Generated by Django 3.2.16 on 2022-12-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0013_auto_20221101_1216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authapiallowlistconfig',
            unique_together={('system_id', 'object_id')},
        ),
        migrations.AlterIndexTogether(
            name='authapiallowlistconfig',
            index_together=set(),
        ),
    ]
